# Generated by Django 5.2.17 on 2026-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sourcery_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='ix_events_stream_id_version',
        ),
        migrations.AlterField(
            model_name='outboxentry',
            name='position',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='outboxentry',
            name='tries_left',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('stream', 'version')},
        ),
    ]
