"""empty message

Revision ID: 6f9fbf30e41f
Revises: 
Create Date: 2022-09-11 13:30:14.538388

"""
import sqlalchemy as sa
from alembic import op

from event_sourcery_sqlalchemy import guid, jsonb

# revision identifiers, used by Alembic.
revision = "6f9fbf30e41f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_sourcery_events",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("uuid", guid.GUID(), nullable=True),
        sa.Column("stream_id", guid.GUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("data", jsonb.JSONB(), nullable=False),
        sa.Column("event_metadata", jsonb.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_sourcery_events_created_at"),
        "event_sourcery_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_sourcery_events_stream_id"),
        "event_sourcery_events",
        ["stream_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_sourcery_events_uuid"),
        "event_sourcery_events",
        ["uuid"],
        unique=True,
    )
    op.create_index(
        "ix_events_stream_id_version",
        "event_sourcery_events",
        ["stream_id", "version"],
        unique=True,
    )
    op.create_table(
        "event_sourcery_outbox_entries",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("data", jsonb.JSONB(), nullable=False),
        sa.Column("tries_left", sa.Integer(), server_default="3", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_event_sourcery_outbox_entries_created_at"),
        "event_sourcery_outbox_entries",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "event_sourcery_snapshots",
        sa.Column("uuid", guid.GUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("stream_id", guid.GUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("data", jsonb.JSONB(), nullable=False),
        sa.Column("event_metadata", jsonb.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_event_sourcery_snapshots_stream_id"),
        "event_sourcery_snapshots",
        ["stream_id"],
        unique=False,
    )
    op.create_table(
        "event_sourcery_streams",
        sa.Column("uuid", guid.GUID(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_sourcery_streams")
    op.drop_index(
        op.f("ix_event_sourcery_snapshots_stream_id"),
        table_name="event_sourcery_snapshots",
    )
    op.drop_table("event_sourcery_snapshots")
    op.drop_index(
        op.f("ix_event_sourcery_outbox_entries_created_at"),
        table_name="event_sourcery_outbox_entries",
    )
    op.drop_table("event_sourcery_outbox_entries")
    op.drop_index("ix_events_stream_id_version", table_name="event_sourcery_events")
    op.drop_index(
        op.f("ix_event_sourcery_events_uuid"), table_name="event_sourcery_events"
    )
    op.drop_index(
        op.f("ix_event_sourcery_events_stream_id"), table_name="event_sourcery_events"
    )
    op.drop_index(
        op.f("ix_event_sourcery_events_created_at"), table_name="event_sourcery_events"
    )
    op.drop_table("event_sourcery_events")
    # ### end Alembic commands ###
