name: Deploy docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "2.1.1"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry==${{ env.POETRY_VERSION }}
      - name: Install deps
        run: poetry install --with=dev --all-extras
      - name: Build docs
        run: poetry run zensical build --clean
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
