name: Publish on Release

on:
  release:
    types: [published]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: "2.1.1"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry==${{ env.POETRY_VERSION }}
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
